<a href="https://colab.research.google.com/github/beyzadurdu6619/ML/blob/main/CountVectorizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
#Count Vectorizer
#Her metni sesi arraya çevirmeliyiz.
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer



In [23]:
df = pd.DataFrame()
df["cumleler"]=["ali bak","ali ata bak","bak ali bak","ali güzel ata bak","ışık ılık süt iç","ışık süt iç","iç ışık iç"]
cv=CountVectorizer(max_features=4)
x=cv.fit_transform(df["cumleler"]).toarray()
print(x)
#YOĞUN OLAN KELİMELERİ YAKALIYOR VE KATEGOEİZE EDİYOR.

[[1 1 0 0]
 [1 1 0 0]
 [1 2 0 0]
 [1 1 0 0]
 [0 0 1 1]
 [0 0 1 1]
 [0 0 2 1]]


In [24]:
cv.get_feature_names_out() #Önemli kelimelere bu şekilde bakabiliyoruz.

array(['ali', 'bak', 'iç', 'ışık'], dtype=object)

In [25]:
#stopwords
stopwords=['fakat','lakin','ancak','acaba', 'ama', 'aslında', 'az', 'bazı', 'belki', 'biri', 'birkaç', 'birşey', 'biz', 'bu', 'çok', 'çünkü', 'da', 'daha', 'de', 'defa', 'diye', 'eğer', 'en', 'gibi', 'hem', 'hep', 'hepsi', 'her', 'hiç', 'için', 'ile', 'ise', 'kez', 'ki', 'kim', 'mı', 'mu', 'mü', 'nasıl', 'ne', 'neden', 'nerde', 'nerede', 'nereye', 'niçin', 'niye', 'o', 'sanki', 'şey', 'siz', 'şu', 'tüm', 've', 'veya', 'ya', 'yani']